config/routes.rb
Rails.application.routes.draw do
  # for chat
  mount ActionCable.server => '/cable'

  get 'user_languages/edit'
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:index, :show, :edit, :update] do
    resources :meetups, only: [:new, :create]
    resources :chats, only: [:index, :show, :create]
  end

  # for chat
  resources :messages, only:[:create]

  resources :user_languages, only: [:edit, :update, :new, :create, :destroy]

  get '/meetups/callback', to: 'meetups#new_event', as: 'new_event'

  resources :meetups, only: [:index, :show, :update] do
    get '/events', to: 'meetups#get_token', as: 'get_token'
    # get '/callback', to: 'meetups#new_event', as: 'new_event'
  end



  post '/vocab_items', to: 'vocab_items#create', defaults: {format: :js}
  resources :vocab_items, except: [:create]


  # for user account page
  get '/my_account', to: "users#account_show", as: 'my_account'
  patch '/my_account', to: "users#account_update"

  get '/style', to: "pages#style"
end

app/models/meetup.rb
class Meetup < ApplicationRecord
  belongs_to :sender, foreign_key: :sender_id, class_name: "User"
  belongs_to :recipient, foreign_key: :recipient_id, class_name: "User"

  belongs_to :sharing_lang, foreign_key: :sharing_lang_id, class_name: "Language"
  belongs_to :seeking_lang, foreign_key: :sharing_lang_id, class_name: "Language"

  validates :date, presence: true
  validates :start_time, presence: true
  validates :duration, presence: true
  validates :location, presence: true
  validates :greeting, length: {maximum: 150}

  def opposite_user(current_user)
    sender == current_user ? recipient : sender
  end

  def end_time
    # returns end time (note: duration in minutes)
    start_time + (duration * 60)
  end

  def meetup_occurred?
    meetup_precise_date = self.date.to_datetime + self.start_time.hour.hour + self.start_time.min.minute + self.duration.minute
    meetup_precise_date < DateTime.now
  end

  def real_start_time
   self.date.to_datetime + self.start_time.hour.hour + self.start_time.min.minute
  end
end

app/controllers/meetups_controller.rb
class MeetupsController < ApplicationController

  def index
    @header_title = "Your Meetups"
    @outbound_meetup_requests = current_user.outbound_meetup_requests
    @inbound_meetup_requests = current_user.inbound_meetup_requests
    @confirmed_meetups = current_user.confirmed_meetups
  end

  def show
    @header_title = "Meetup Info"
    @meetup = Meetup.find(params[:id])

  end

  def new
    @header_title = "Request a Meetup"
    @user = User.find(params[:user_id])
    @meetup = Meetup.new
    @seeking_langs = @user.user_languages.filter(&:sharing).map {|user_languages| user_languages.language}
    @sharing_langs = current_user.user_languages.filter(&:sharing).map {|user_languages| user_languages.language}
    # @seeking_langs = @user.user_languages.filter(&:sharing).map {|user_languages| user_languages.language}.collect {|l| [ l.name, l.id ] }
    # @sharing_langs = current_user.user_languages.filter(&:sharing).map {|user_languages| user_languages.language}.collect {|l| [ l.name, l.id ] }

  end

  def create
    @user = User.find(params[:user_id])
    @meetup = Meetup.new(meetup_params)
    # seeking_l =  Language.find(params[:meetup][:seeking_lang].to_i)
    @meetup.sharing_lang = Language.find(params[:meetup][:sharing_lang].to_i)
    @meetup.seeking_lang_id = params[:meetup][:seeking_lang].to_i
    # @meetup.seeking_lang_id = seeking_l.id

    @meetup.sender = current_user

    @meetup.recipient = @user
    @seeking_langs = @user.user_languages.filter(&:sharing).map {|user_languages| user_languages.language}.collect {|l| [ l.name, l.id ] }
    @sharing_langs = current_user.user_languages.filter(&:sharing).map {|user_languages| user_languages.language}.collect {|l| [ l.name, l.id ] }

    if @meetup.save!

      redirect_to meetup_path(@meetup)
    else
      render :new
    end
  end

  def update
    @meetup = Meetup.find(params[:id])
    @meetup.update_attribute(:confirmed, true)

    respond_to do |format|
      format.js
    end
  end

  def get_token
    current_user.update(pending_event_confirmation: params[:meetup_id])
    client = Signet::OAuth2::Client.new(client_options)
    redirect_to client.authorization_uri.to_s
  end

  def new_event
    client = Signet::OAuth2::Client.new(client_options)

    client.code = params[:code]

    response = client.fetch_access_token!

    session[:authorization] = response
    client.update!(session[:authorization])

    service = Google::Apis::CalendarV3::CalendarService.new
    service.authorization = client


    # @user = User.find(params[:user_id])
    @meetup = Meetup.find(current_user.pending_event_confirmation)
    starting_at = @meetup.date.to_datetime + @meetup.start_time.hour.hour + @meetup.start_time.min.minute
    ends_at     = starting_at + @meetup.duration.minute

    event = Google::Apis::CalendarV3::Event.new({
      start: Google::Apis::CalendarV3::EventDateTime.new(date_time: starting_at.rfc3339),
      end: Google::Apis::CalendarV3::EventDateTime.new(date_time: ends_at.rfc3339),
      summary: "Meetup with #{@meetup.sender.first_name} at #{@meetup.location}"
    })


    # event = Google::Apis::CalendarV3::Event.new({
    #   start: Google::Apis::CalendarV3::EventDateTime.new(date_time: DateTime.now),
    #   end: Google::Apis::CalendarV3::EventDateTime.new(date_time: DateTime.now + @meetup.duration.minute),
    #   summary: "Meetup with #{@meetup.sender.first_name}"
    # })

    # event = Google::Apis::CalendarV3::Event.new({
    #   start: Google::Apis::CalendarV3::EventDateTime.new(date: @meetup.start_time.to_date),
    #   end: Google::Apis::CalendarV3::EventDateTime.new(date: @meetup.end_time.to_date),
    #   summary: "Meetup with #{@meetup.sender.first_name}"
    # })

    service.insert_event("leagrelou@gmail.com", event)

    redirect_to meetups_url
  end

  private

  def client_options
    {
      client_id: ENV["GOOGLE_CLIENT_ID"],
      client_secret: ENV["GOOGLE_CLIENT_SECRET"],
      authorization_uri: 'https://accounts.google.com/o/oauth2/auth',
      token_credential_uri: 'https://accounts.google.com/o/oauth2/token',
      scope: Google::Apis::CalendarV3::AUTH_CALENDAR,
      redirect_uri: new_event_url
    }
  end

  def meetup_params
    params.require(:meetup).permit(:date, :start_time, :duration, :location, :greeting)
  end

  def confirmed_meetup_params
    params.require(:meetup).permit(:confirmed)
  end
end

app/views/meetups/index.html.erb
<div class="container mt-3">
  <h3 class="bh-text-bg">Upcoming</h3>
  <% if @confirmed_meetups == [] %>
    <p>There is no upcoming meetup</p>
  <% else %>
    <% @confirmed_meetups.each do |m| %>
      <% if !m.meetup_occurred? %>
        <%= link_to meetup_path(m) do %>
          <div class="bh-card-meetup-index">
            <div class="image-user">
              <%= image_tag m.opposite_user(current_user).photo || "https://images.unsplash.com/photo-1534528741775-53994a69daeb?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=700&q=80", class: "bh-avatar-sm" %>
            </div>
            <div class="user-info">
              <p style="font-weight: bold; color: black;"><%=  m.opposite_user(current_user).first_name %></p>
              <p style="font-weight: light;">confirmed</p>
            </div>
            <div class="date-languages">
              <p class="date"><%=  m.date.strftime("%b %d, %Y") %></p>
              <!-- sharing -->
              <div class="languages">
                <div class="language-part">
                  <% m.opposite_user(current_user).user_languages.filter(&:sharing).each do |user_language| %>
                    <div class="lang-pro">
                      <div class="language-code"><%=  user_language.language.code %></div>
                      <div class="progress-bar">
                        <div style="background-color: #DDDDDD; width: 20px;">
                          <div style ="width: <%= user_language.level %>; background-color: #80BD9E; height: 7px;"></div>
                        </div>
                      </div>
                    </div>
                  <% end %>
                </div>
                <!-- practicing -->
                <div class="language-part">
                  <% m.opposite_user(current_user).user_languages.filter(&:seeking).each do |user_language| %>
                    <div class="lang-pro-seeking">
                      <div class="language-code"><%=  user_language.language.code %></div>
                      <div class="progress-bar">
                        <div style="background-color: #DDDDDD; width: 20px;">
                          <div style ="width: <%= user_language.level %>; background-color: #F49342; height: 7px;"></div>
                        </div>
                      </div>
                    </div>
                  <% end %>
                </div>
              </div>
            </div>
          </div>
          <hr class="meetup-index-hr">
        <% end %>
      <% end %>
    <% end %>
  <% end %>

  <h3 class="bh-text-bg">Awaiting your confirmation</h3>
    <% @inbound_meetup_requests.each do |m| %>
      <%= link_to meetup_path(m) do %>
        <div class="bh-card-meetup-index">
          <div class="image-user">
            <%= image_tag m.opposite_user(current_user).photo || "https://images.unsplash.com/photo-1534528741775-53994a69daeb?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=700&q=80", class: "bh-avatar-sm" %>
          </div>

          <div class="user-info">
            <p style="font-weight: bold; color: black;"><%=  m.opposite_user(current_user).first_name %></p>
            <p style="font-weight: light;">pending</p>
          </div>
          <!-- </div> -->
          <div class="date-languages">
            <p class="date"><%=  m.date.strftime("%b %d, %Y") %></p>
            <!-- sharing -->
            <div class="languages">
              <div class="language-part">
                <% m.opposite_user(current_user).user_languages.filter(&:sharing).each do |user_language| %>
                  <div class="lang-pro">
                    <div class="language-code"><%=  user_language.language.code %></div>
                    <div class="progress-bar">
                      <div style="background-color: #DDDDDD; width: 20px;">
                        <div style ="width: <%= user_language.level %>; background-color: #80BD9E; height: 7px;"></div>
                      </div>
                    </div>
                  </div>
                <% end %>
              </div>
              <!-- practicing -->
              <div class="language-part">
                <% m.opposite_user(current_user).user_languages.filter(&:seeking).each do |user_language| %>
                  <div class="lang-pro-seeking">
                    <div class="language-code"><%=  user_language.language.code %></div>
                    <div class="progress-bar">
                      <div style="background-color: #DDDDDD; width: 20px;">
                        <div style ="width: <%= user_language.level %>; background-color: #F49342; height: 7px;"></div>
                      </div>
                    </div>
                  </div>
                <% end %>
              </div>
            </div>
          </div>
        </div>
        <hr class="meetup-index-hr">
      <% end %>
    <% end %>


  <h3 class="bh-text-bg">Request by you</h3>
    <% @outbound_meetup_requests.each do |m| %>
      <%= link_to meetup_path(m) do %>
        <div class="bh-card-meetup-index">
          <div class="image-user">
            <%= image_tag m.opposite_user(current_user).photo || "https://images.unsplash.com/photo-1534528741775-53994a69daeb?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=700&q=80", class: "bh-avatar-sm" %>
          </div>

          <div class="user-info">
            <p style="font-weight: bold; color: black;"><%=  m.opposite_user(current_user).first_name %></p>
            <p style="font-weight: light;">pending</p>
          </div>
          <!-- </div> -->
          <div class="date-languages">
            <p class="date"><%=  m.date.strftime("%b %d, %Y") %></p>
            <!-- sharing -->
            <div class="languages">
              <div class="language-part">
                <% m.opposite_user(current_user).user_languages.filter(&:sharing).each do |user_language| %>
                  <div class="lang-pro">
                    <div class="language-code"><%=  user_language.language.code %></div>
                    <div class="progress-bar">
                      <div style="background-color: #DDDDDD; width: 20px;">
                        <div style ="width: <%= user_language.level %>; background-color: #80BD9E; height: 7px;"></div>
                      </div>
                    </div>
                  </div>
                <% end %>
              </div>
              <!-- practicing -->
              <div class="language-part">
                <% m.opposite_user(current_user).user_languages.filter(&:seeking).each do |user_language| %>
                  <div class="lang-pro-seeking">
                    <div class="language-code"><%=  user_language.language.code %></div>
                    <div class="progress-bar">
                      <div style="background-color: #DDDDDD; width: 20px;">
                        <div style ="width: <%= user_language.level %>; background-color: #F49342; height: 7px;"></div>
                      </div>
                    </div>
                  </div>
                <% end %>
              </div>
            </div>
          </div>
        </div>
          <hr class="meetup-index-hr">
      <% end %>
    <% end %>


  <h3 class="bh-text-bg">Past</h3>
  <% if @confirmed_meetups.any? %>
    <p>There is no past meetup</p>
    <hr>
  <% else %>
    <% @confirmed_meetups.select { |cm| !cm.meetup_occurred? }.reverse.each do |m| %>
      <%= link_to meetup_path(m) do %>
        <div class="bh-card-meetup-index">
          <div class="image-user">
            <%= image_tag m.opposite_user(current_user).photo || "https://images.unsplash.com/photo-1534528741775-53994a69daeb?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=700&q=80", class: "bh-avatar-sm" %>
          </div>

          <div class="user-info">
            <p style="font-weight: bold; color: black;"><%=  m.opposite_user(current_user).first_name %></p>
            <p style="font-weight: light;">confirmed</p>
          </div>
          <!-- </div> -->
          <div class="date-languages">
            <div class="date"><%=  m.date.strftime("%b %d, %Y") %></div>
            <!-- sharing -->
            <div class="date-languages">
            <p class="date"><%=  m.date %></p>
            <!-- sharing -->
            <div class="languages">
              <div class="language-part">
                <% m.opposite_user(current_user).user_languages.filter(&:sharing).each do |user_language| %>
                  <div class="lang-pro">
                    <div class="language-code"><%=  user_language.language.code %></div>
                    <div class="progress-bar">
                      <div style="background-color: #DDDDDD; width: 20px;">
                        <div style ="width: <%= user_language.level %>; background-color: #80BD9E; height: 7px;"></div>
                      </div>
                    </div>
                  </div>
                <% end %>
              </div>
              <!-- practicing -->
              <div class="language-part">
                <% m.opposite_user(current_user).user_languages.filter(&:seeking).each do |user_language| %>
                  <div class="lang-pro-seeking">
                    <div class="language-code"><%=  user_language.language.code %></div>
                    <div class="progress-bar">
                      <div style="background-color: #DDDDDD; width: 20px;">
                        <div style ="width: <%= user_language.level %>; background-color: #F49342; height: 7px;"></div>
                      </div>
                    </div>
                  </div>
                <% end %>
              </div>
            </div>
          </div>
          </div>
        </div>
        <hr class="meetup-index-hr">
      <% end %>
    <% end %>
  <% end %>

</div>

app/views/meetups/new.html.erb
<div class="container">

  <div class="bh-flex-container">
    <div class="bh-flex-element">
      <img class="bh-avatar-lg" src="<%= @user.photo %>">
    </div>
    <div class="bh-flex-element mt-4">
      <h3><b><%= @user.first_name %></b></h3>
      <p><b>Availability:</b> <br> <%= @user.availibility %></p>
    </div>
  </div>

  <%= simple_form_for [@user, @meetup] do |f| %>
    <%= f.input :seeking_lang, as: :select, label: "I want to practice", collection: @seeking_langs, include_blank: false, include_hidden: false  %>
    <%= f.input :sharing_lang, as: :select, label: "I want to share", collection: @sharing_langs, include_blank: false, include_hidden: false %>
    <%= f.input :date, label: "Date", html5: true, required: true %>
    <%= f.input :start_time, label: "Start Time", :as => :time, :minute_step => 15 %>
    <%= f.input :duration, label: "Duration", collection: [['1 hour', 60], ['1.5 hours', 90], ['2 hours', 120]], include_blank: false, include_hidden: false %>
    <%= f.input :location, label: "Location", required: true %>
    <%= f.input :greeting, label: "Greeting message", error: "Message too long (under 150 characters)" %>
    <%= f.submit "Send request", class: "bh-btn-solid-lg-show mb-4" %>
  <% end %>

</div>

app/views/meetups/show.html.erb
<div class="container">

  <div class="bh-flex-container">
    <div class="bh-flex-element">
      <%= link_to user_path(@meetup.opposite_user(current_user)) do  %>
        <img class="bh-avatar-lg" src="<%= @meetup.opposite_user(current_user).photo %>">
      <% end %>
    </div>

    <div class="bh-flex-element">
      <h3><b><%= @meetup.opposite_user(current_user).first_name %></b></h3>
      <% if @meetup.confirmed %>
        <p>Status: Confirmed</p>
      <% else %>
        <p>Status: <span id="pending">Pending</span></p>
      <% end %>
      <p class="mt-n2"> <%=  Language.find(@meetup.seeking_lang_id).code %> | <%= @meetup.sharing_lang.code %> </p>
    </div>
  </div>

  <div class="bh-text-body">
    <h3><b>When</b></h3>
    <p>
      <%= "#{@meetup.date.strftime("%a, %b %d %Y")}" %>  ,
      <%= "#{@meetup.start_time.strftime('%l:%M')} - #{@meetup.end_time.strftime('%l:%M %p')}" %>
    </p>

    <h3><b>Where</b></h3>
    <div class="d-flex justify-content-end mb-n4" ><%= link_to "Open in Maps >>", "#" %></div>
    <p>
      <%= @meetup.location %>
    </p>
  </div>

<!-- End of container -->
</div>

<div class="mt-n2" >
<%= image_tag "cafe.png", style:"width:100%" %>
</div>

<!-- Start of new container -->
<div class="container">

  <div class="bh-text-body mt-3">
    <h3><b>Greeting message</b></h3>
    <p><%= @meetup.greeting %></p>
    <div class="d-flex justify-content-end mt-n1"><%= link_to "Open Chat >>", user_chats_path(current_user, other_user: @meetup.opposite_user(current_user)), method: :post %></div>
  </div>

<div class="container">
    <% if @meetup.confirmed && !@meetup.meetup_occurred? %>
      <%= link_to "" do %>
        <button type="button" class="bh-btn-solid-lg-show">
          Reschedule / Cancel
        </button>
      <% end %>
    <% elsif !@meetup.confirmed && @meetup.sender == current_user %>
      <%= link_to "" do %>
        <button type="button" class="bh-btn-solid-lg-show">
          Reschedule / Cancel
        </button>
      <% end %>
    <% elsif @meetup.confirmed && @meetup.meetup_occurred? %>
      <%= link_to "" do %>
        <button type="button" class="bh-btn-solid-lg-show">
          Leave a review
        </button>
      <% end %>
    <% else %>
      <%= link_to meetup_path(@meetup), method: :patch, remote: true do %>
        <button id="confirmed-button" type="button" class="bh-btn-solid-lg-show" data-toggle="modal" data-target="#exampleModal">
          Confirm meetup
        </button>
      <% end %>
      <%= link_to "", remote: true do %>
        <button id="cancel-button" type="button" class="bh-btn-solid-lg-show d-none">
          Reschedule / Cancel
        </button>
      <% end %>
    <% end %>
  </div>
  <br>
</div>

app/views/meetups/showOLD.html.erb
<!-- <div class="container">

  <div class="bh-meetup-show-container">
    <div class="bh-meetup-show-avatar"> -->
      <!-- <img class="bh-avatar-lg" src="<%= @meetup.opposite_user(current_user).photo %>"> -->
<!--     </div>
    <div class="bh-meetup-show-info">
      <h3><b>With <%= @meetup.opposite_user(current_user).first_name %></b></h3>
      <% if @meetup.confirmed %>
        <p>Status: Confirmed</p>
      <% else %>
        <p>Status: <span id="pending">Pending</span></p>
      <% end %>
    </div>
  </div> -->

<!--   <div class="mt-3">
    <div class="meetup-languagues">
      <div><i class="fas fa-globe"></i></div>
      <div class="meetup-show-sharing">
        <% @meetup.opposite_user(current_user).user_languages.filter(&:sharing).each do |user_language| %>
          <p style="margin-left: 7px;"><%=  user_language.language.code %> </p>
        <% end %>
      </div>
      <div class="meetup-show-seeking">
        <% @meetup.opposite_user(current_user).user_languages.filter(&:seeking).each do |user_language| %>
          <p style="margin-left: 7px;"> | <%=  user_language.language.code %></p>
        <% end %>
      </div>
    </div> -->
<!-- 
    <p>When: <%= "#{@meetup.date.strftime("%d/%m/%Y")}, #{@meetup.start_time.strftime('%H:%M')} - #{@meetup.end_time.strftime('%H:%M')}" %></p>
    <p>Where: <%= @meetup.location %></p>
    <% if @meetup.confirmed %>
      <div class="d-flex justify-content-end"><%= link_to "add event to calendar", meetup_get_token_url(@meetup)  %></div>
    <% end %> -->
   <!--  <%= image_tag "https://res.cloudinary.com/dgxkozw6v/image/upload/v1575058085/cafe-myriade_kd2faq.png", style:'height:200px; width:500px; margin-bottom:20px; object-fit:cover;' %>
    <div class="d-flex justify-content-end"><%= link_to "Open in Maps >>", "#" %></div>
  </div> -->
<!-- 
  <div>
    <h3>Greeting message:</h3>
    <p><%= @meetup.greeting %></p> -->
    <div class="d-flex justify-content-end"><%= link_to "Reply in Messages >>", "#" %></div>
  <div>

  <br>
  <!-- <div class="container">
    <% if @meetup.confirmed && !@meetup.meetup_occurred? %>
      <%= link_to "" do %>
        <button type="button" class="bh-btn-solid-lg-show">
          Reschedule / Cancel
        </button>
      <% end %>
    <% elsif !@meetup.confirmed && @meetup.sender == current_user %>
      <%= link_to "" do %>
        <button type="button" class="bh-btn-solid-lg-show">
          Reschedule / Cancel
        </button>
      <% end %>
    <% elsif @meetup.confirmed && @meetup.meetup_occurred? %>
      <%= link_to "" do %>
        <button type="button" class="bh-btn-solid-lg-show">
          Leave a review
        </button>
      <% end %>
    <% else %>
      <%= link_to meetup_path(@meetup), method: :patch, remote: true do %>
        <button id="confirmed-button" type="button" class="bh-btn-solid-lg-show" data-toggle="modal" data-target="#exampleModal">
          Confirm meetup
        </button>
      <% end %>
      <%= link_to "", remote: true do %>
        <button id="cancel-button" type="button" class="bh-btn-solid-lg-show d-none">
          Reschedule / Cancel
        </button>
      <% end %>
    <% end %>
  </div> -->

  <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <div class="d-flex align-items-center">
            <img class="ml-5 bh-avatar-sm" src="<%= @meetup.opposite_user(current_user).photo %>">
            <h5 class="ml-4 modal-title" id="exampleModalLabel">Meetup with <%= @meetup.sender.first_name %> confirmed!</h5>
          </div>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <div class="d-flex justify-content-end"><%= link_to "Add event to Google calendar", meetup_get_token_url(@meetup), class: "bh-btn-outline-lg"  %></div>
          <div class="d-flex justify-content-end"><%= link_to "Message #{@meetup.sender.first_name} in chat", user_chats_path(current_user), class: "bh-btn-outline-lg" %></div>
        </div>
        <div class="modal-footer">
          <%= link_to "Go back to my meetups page", meetups_path, class: "bh-btn-solid-lg-show" %>
        </div>
      </div>
    </div>
  </div>
  
</div>

app/views/meetups/update.js.erb
pending = document.querySelector("#pending");
pending.innerText = "Confirmed";

confirmedButton = document.querySelector("#confirmed-button");
confirmedButton.classList.add("d-none")

cancelButton = document.querySelector("#cancel-button");
cancelButton.classList.remove("d-none")