config/routes.rb
Rails.application.routes.draw do
  # for chat
  mount ActionCable.server => '/cable'

  get 'user_languages/edit'
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:index, :show, :edit, :update] do
    resources :meetups, only: [:new, :create]
    resources :chats, only: [:index, :show, :create]
  end

  # for chat
  resources :messages, only:[:create]

  resources :user_languages, only: [:edit, :update, :new, :create, :destroy]

  get '/meetups/callback', to: 'meetups#new_event', as: 'new_event'

  resources :meetups, only: [:index, :show, :update] do
    get '/events', to: 'meetups#get_token', as: 'get_token'
    # get '/callback', to: 'meetups#new_event', as: 'new_event'
  end



  post '/vocab_items', to: 'vocab_items#create', defaults: {format: :js}
  resources :vocab_items, except: [:create]


  # for user account page
  get '/my_account', to: "users#account_show", as: 'my_account'
  patch '/my_account', to: "users#account_update"

  get '/style', to: "pages#style"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :user_languages
  has_many :languages, through: :user_languages

  has_many :user_reviews, foreign_key: :user_id, class_name: "Review"
  has_many :authored_reviews, foreign_key: :author_id, class_name: "Review"


  # before_save :lowercase_city
  has_many :meetups, as: :sender
  has_many :meetups, as: :recipient

  # for chat
  has_many :messages
  has_many :subscriptions
  has_many :chats, through: :subscriptions

  has_many :vocab_items

  def existing_chats_users
    existing_chat_users = []
    self.chats.each do |chat|
    existing_chat_users.concat(chat.subscriptions.where.not(user_id: self.id).map {|subscription| subscription.user})
    end
    existing_chat_users.uniq
  end

  # returns all users excluding the user this method is called on
  def all_users_except_me
    User.where.not(id: id)
  end

  def meetups
    Meetup.where("sender_id = ? OR recipient_id = ?", id, id)
  end

  def outbound_meetup_requests
    Meetup.where("sender_id = ? AND confirmed = false", id)
  end

  def inbound_meetup_requests
    Meetup.where("recipient_id = ? AND confirmed = false", id)
  end

  def confirmed_meetups
    Meetup.where("(sender_id = ? OR recipient_id = ?) AND confirmed = true", id, id).order(:date)
  end

  private

  def lowercase_city
    return if self.city.nil?

    self.city = self.city.lowercase
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @header_title = "Partner Search"
    if params[:city].present?

      city = params[:city]
      language_id = params[:language]

      # @users = User.joins(:user_languages).where(city: city, user_languages: { language_id: language, sharing: true })
      @users = User.joins(:user_languages).where(
        "city ILIKE :city
        AND user_languages.language_id = :language_id
        AND user_languages.sharing = true
      ", city: city, language_id: language_id)

    else
      @users = User.where.not("id = ?", current_user.id)
    end
  end

  def show
    @header_title = "User Info"
    @user = User.find(params[:id])
    @user_languages = UserLanguage.where("user_id = ?", params[:id])
    @title = "Bonjourhi | " + @user.first_name + " " + @user.last_name
  end

  def edit
    @user = User.find(params[:id])
    @header_title = "Edit Your Info"
  end

  def account_show
    @user = current_user
    @sharing_user_langs = @user.user_languages.filter(&:sharing)
    @seeking_user_langs = @user.user_languages.filter(&:seeking)
  end

  def account_update
  end

  private

  def user_params
    # params.require(:user).permit(:)
  end

end

app/views/users/account_show.html.erb
<div class="container">
  
  <div class="bh-flex-container"> 
    <div class="bh-flex-element">  
      <img class="bh-avatar-lg" src="<%= @user.photo %>">
    </div>
    <div class="bh-flex-element mt-4">
      <h3><b><%= @user.first_name %></b></h3>
      <p class="mt-n1">Past Meetups: <%= @user.num_of_past_meetups %></p>
    </div>
  </div>
  
  <div class="bh-flex-container">  
    
    <div class="bh-flex-element">  
      <h3><b>Sharing</b></h3> 
      <% @user.user_languages.filter(&:sharing).each do |user_language| %> 
        <div class="lang-pro d-flex justify-content-between">
          <span style="width: 1px">
            <%= user_language.language.code %>            
          </span>
          <div class="d-flex align-items-center justify-content-flex-left">
            <div style="background-color: #DDDDDD; width: 50px; height: 13px;">
              <div
                style ="width: <%= user_language.level %>; background-color: #80BD9E; height: 13px;">
              </div>
            </div>
          </div>
          <%= button_to user_language_path(user_language), method: :delete do %>
            <i class="fas fa-minus-circle mr-4"></i>
          <% end %>                 
        </div>
      <% end %> 
      <%= link_to new_user_language_path(ul_type: 'sharing') do %>
        <i class="fas fa-plus-circle"></i>
      <% end %>   
    </div>
    
    <div class="bh-flex-element">  
      <h3><b>Practicing</b></h3> 
      <% @user.user_languages.filter(&:seeking).each do |user_language| %> 
        <div class="lang-pro d-flex justify-content-between">
          <span style="width: 1px">
            <%= user_language.language.code %>            
          </span>
          <div class="d-flex align-items-center justify-content-flex-left">
            <div style="background-color: #DDDDDD; width: 50px; height: 13px;">
              <div
                style ="width: <%= user_language.level %>; background-color: #F49342; height: 13px;">
              </div>
            </div>
          </div>
          <%= button_to user_language_path(user_language), method: :delete do %>
            <i class="fas fa-minus-circle mr-4"></i>
          <% end %>           
        </div>
      <% end %>
      <%= link_to new_user_language_path(ul_type: 'seeking') do %>
        <i class="fas fa-plus-circle"></i>
      <% end %>   
    </div> 
    
  </div>
    
  <div class="bh-text-body">
    <h3><b>Bio</b></h3>
    <p><%= @user.bio %></p>
  </div>

</div>


<div class="bh-button-sticky-bottom">
  <%= link_to "Edit Your profile", edit_user_path(@user), class: "bh-btn-solid-lg-sticky" %>
</div>

app/views/users/edit.html.erb
<div class="container mt-4">
<%= simple_form_for @user do |f| %>
<%= f.input :first_name %>
<%= f.input :last_name %>
<%= f.input :city%>
<%= f.input :email%>
<%= f.submit class: "bh-btn-solid-lg mt-4" %>
<% end %>
</div>

app/views/users/index.html.erb
<% @users.each do |user| %>
  <%= link_to user_path(user) do %>
    <%= render partial: 'shared/user-index-card3', locals: {user: user} %>
  <% end %>
<% end %>

app/views/users/old_show.html.erb
<div class="container">

  <div class="mt-4 d-flex justify-content-around">
    <div class="col-6">
      <img class="bh-avatar-lg" src="<%= @user.photo %>">
    </div>
    <div class="mt-3 col-6">
      <h3 class=""><b><%= @user.first_name %></b></h3>
      <p><%= @user.city %></p>
    </div>
  </div>

  <div class="mt-4 d-flex justify-content-around">
    <div class="col-6">
      <h3><b>Sharing</b></h3>
    </div>
    <div class="col-6">
      <ul>
        <% @user_languages.filter(&:sharing).each do |ul| %>
        <li><%= ul.language.name %> (<%= ul.proficiency %>)
        <% end %>
      </ul>
    </div>
  </div>

  <div class="mt-4 d-flex justify-content-around">
    <div class="col-6">
      <h3><b>Practicing</b></h3>
    </div>
    <div class="col-6">
      <ul>
        <% @user_languages.filter(&:seeking).each do |ul| %>
          <li><%= ul.language.name %> (<%= ul.proficiency %>)
        <% end %>
      </ul>
    </div>
  </div>

  <div class="mt-4 d-flex justify-content-around">
    <div class="col-12">
      <h3><b>Bio</b></h3>
    </div>
  </div>

  <div class="mt-2">
    <div class="col-12">
      <p><%= @user.bio %></p>
    </div>
  </div>

   <!-- end of rows -->

  <div class="container">
    <% if @user != current_user %>
      <button class="bh-btn-solid-lg-show"><%= link_to "Request a Meetup", new_user_meetup_path(@user) %></button>
    <% else %>
      <p><%= link_to "Edit #{@user.first_name}'s profile", edit_user_path(@user) %></p>
    <% end %>
  </div>

</div>

app/views/users/show.html.erb
<div class="container">

  <div class="bh-flex-container">
    <div class="bh-flex-element">
      <img class="bh-avatar-lg" src="<%= @user.photo %>">
    </div>
    <div class="bh-flex-element mt-4">
      <h3><b><%= @user.first_name %></b></h3>
      <p class="mt-n1">Past Meetups: <%= @user.num_of_past_meetups %></p>
    </div>
  </div>

  <div class="bh-flex-container">

    <div class="bh-flex-element">
      <h3><b>Sharing</b></h3>
      <% @user.user_languages.filter(&:sharing).each do |user_language| %>
        <div class="lang-pro d-flex justify-content-between">
          <span style="width: 1px">
            <%= user_language.language.code %>
          </span>
          <div class="d-flex align-items-center justify-content-flex-left">
            <div style="background-color: #DDDDDD; width: 50px; height: 13px;">
              <div
                style ="width: <%= user_language.level %>; background-color: #80BD9E; height: 13px;">
              </div>
            </div>
          </div>
          <br>
          <i></i>
          <br>
        </div>
      <% end %>
    </div>

    <div class="bh-flex-element">
      <h3><b>Practicing</b></h3>
      <% @user.user_languages.filter(&:seeking).each do |user_language| %>
        <div class="lang-pro d-flex justify-content-between">
          <span style="width: 1px">
            <%= user_language.language.code %>
          </span>
          <div class="d-flex align-items-center justify-content-flex-left">
            <div style="background-color: #DDDDDD; width: 50px; height: 13px;">
              <div
                style ="width: <%= user_language.level %>; background-color: #F49342; height: 13px;">
              </div>
            </div>
          </div>
          <br>
          <i></i>
          <br>
        </div>
      <% end %>
    </div>

  </div>

  <div class="bh-text-body">
    <h3><b>Bio</b></h3>
    <p><%= @user.bio %></p>
  </div>



  <div class="bh-text-body">
    <h3><b>Reviews</b></h3>
    <% @user.user_reviews.each do |r|%>
      <p><%= link_to user_path(r.author) do  %>
          <%= image_tag r.author.photo, class: "bh-avatar-xxs" %>
          <% end %>
          <%= r.author.first_name %> | <%= r.date_to_string %></b></p> <p> <%= r.content %></p>
    <% end %>
  </div>
</div>

<% if @user != current_user %>
  <div class="bh-button-sticky-bottom">
    <%= link_to "Request a Meetup", new_user_meetup_path(@user), class: "bh-btn-solid-lg-sticky" %>
  </div>
<% else %>
  <p><%= link_to "Edit #{@user.first_name}'s profile", edit_user_path(@user) %></p>
<% end %>