config/routes.rb
Rails.application.routes.draw do
  # for chat
  mount ActionCable.server => '/cable'

  get 'user_languages/edit'
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:index, :show, :edit, :update] do
    resources :meetups, only: [:new, :create]
    resources :chats, only: [:index, :show, :create]
  end

  # for chat
  resources :messages, only:[:create]

  resources :user_languages, only: [:edit, :update, :new, :create, :destroy]

  get '/meetups/callback', to: 'meetups#new_event', as: 'new_event'

  resources :meetups, only: [:index, :show, :update] do
    get '/events', to: 'meetups#get_token', as: 'get_token'
    # get '/callback', to: 'meetups#new_event', as: 'new_event'
  end



  post '/vocab_items', to: 'vocab_items#create', defaults: {format: :js}
  resources :vocab_items, except: [:create]


  # for user account page
  get '/my_account', to: "users#account_show", as: 'my_account'
  patch '/my_account', to: "users#account_update"

  get '/style', to: "pages#style"
end

app/views/shared/_bh-language-select.html.erb
_bh-language-select.html.erb
<select data-placeholder="Choose a Language...">
  <option value="AF">Afrikanns</option>
  <option value="SQ">Albanian</option>
  <option value="AR">Arabic</option>
  <option value="HY">Armenian</option>
  <option value="EU">Basque</option>
  <option value="BN">Bengali</option>
  <option value="BG">Bulgarian</option>
  <option value="CA">Catalan</option>
  <option value="KM">Cambodian</option>
  <option value="ZH">Chinese (Mandarin)</option>
  <option value="HR">Croation</option>
  <option value="CS">Czech</option>
  <option value="DA">Danish</option>
  <option value="NL">Dutch</option>
  <option value="EN">English</option>
  <option value="ET">Estonian</option>
  <option value="FJ">Fiji</option>
  <option value="FI">Finnish</option>
  <option value="FR">French</option>
  <option value="KA">Georgian</option>
  <option value="DE">German</option>
  <option value="EL">Greek</option>
  <option value="GU">Gujarati</option>
  <option value="HE">Hebrew</option>
  <option value="HI">Hindi</option>
  <option value="HU">Hungarian</option>
  <option value="IS">Icelandic</option>
  <option value="ID">Indonesian</option>
  <option value="GA">Irish</option>
  <option value="IT">Italian</option>
  <option value="JA">Japanese</option>
  <option value="JW">Javanese</option>
  <option value="KO">Korean</option>
  <option value="LA">Latin</option>
  <option value="LV">Latvian</option>
  <option value="LT">Lithuanian</option>
  <option value="MK">Macedonian</option>
  <option value="MS">Malay</option>
  <option value="ML">Malayalam</option>
  <option value="MT">Maltese</option>
  <option value="MI">Maori</option>
  <option value="MR">Marathi</option>
  <option value="MN">Mongolian</option>
  <option value="NE">Nepali</option>
  <option value="NO">Norwegian</option>
  <option value="FA">Persian</option>
  <option value="PL">Polish</option>
  <option value="PT">Portuguese</option>
  <option value="PA">Punjabi</option>
  <option value="QU">Quechua</option>
  <option value="RO">Romanian</option>
  <option value="RU">Russian</option>
  <option value="SM">Samoan</option>
  <option value="SR">Serbian</option>
  <option value="SK">Slovak</option>
  <option value="SL">Slovenian</option>
  <option value="ES">Spanish</option>
  <option value="SW">Swahili</option>
  <option value="SV">Swedish </option>
  <option value="TA">Tamil</option>
  <option value="TT">Tatar</option>
  <option value="TE">Telugu</option>
  <option value="TH">Thai</option>
  <option value="BO">Tibetan</option>
  <option value="TO">Tonga</option>
  <option value="TR">Turkish</option>
  <option value="UK">Ukranian</option>
  <option value="UR">Urdu</option>
  <option value="UZ">Uzbek</option>
  <option value="VI">Vietnamese</option>
  <option value="CY">Welsh</option>
  <option value="XH">Xhosa</option>
</select>

app/views/shared/_bh-nav-footer.html.erb
<% if controller_name != "pages" %>
  <div 
    class="bh-pushdown-content">
  </div>
<% end %>

<div class="bh-nav-footer">
  <div>
    <%= link_to root_path do %>
      <i class="fas fa-search bh-nav-i"></i>
    <% end %>
  </div>
  <div>
    <%= link_to meetups_path do %>
      <i class="fas fa-calendar-check bh-nav-i"></i>
    <% end %>
  </div>
  <div>
    <%= link_to vocab_items_path do %>
      <i class="fas fa-book bh-nav-i"></i>
    <% end %>
  </div>
  <div>
    <% if user_signed_in? %>
      <%= link_to user_chats_path(current_user) do %>
        <i class="fas fa-envelope bh-nav-i"></i>
      <% end %>
    <% else %>
      <%= link_to new_user_session_path do %>
        <i class="fas fa-envelope bh-nav-i"></i>
      <% end %>
    <% end %>
  </div>
  <div>
    <% if user_signed_in? %>
      <%= link_to my_account_path do %>
        <i class="fas fa-user bh-nav-i"></i>
      <% end %>
    <% else %>
      <%= link_to new_user_session_path do %>
        <i class="fas fa-user bh-nav-i"></i>
      <% end %>
    <% end %>
  </div>
</div>

app/views/shared/_bh-nav-header.html.erb
<% if controller_name != "pages" %>

<div class="bh-nav-header"> 
  <div class="bh-nav-back">
    <%= link_to :back do %>
      <i class="fas fa-angle-left bh-nav-i"></i>
    <% end %>
  </div> 
  
  <div>
    <h3 class="bh-nav-title"> <%= @header_title %> </h3>
  </div>
  
  <div class="signin">
    <% if user_signed_in? %>
      <%= link_to "Logout", destroy_user_session_path, method: :delete %>
    <% else %>
      <%= link_to "Login", new_user_session_path%>
    <% end %>
  </div>
</div>
<<<<<<< HEAD
<<<<<<< HEAD
=======

<% end %>
>>>>>>> master
=======

<% end %>

>>>>>>> master

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_home_bh-nav-header.html.erb
<div class="bh-nav-header"> 
  <div class="bh-nav-back">
    <%= link_to :back do %>
      <i class="fas fa-angle-left bh-nav-i-home"></i>
    <% end %>
  </div> 
  
  <div>
    <h3 class="bh-nav-title"> <%= @header_title %> </h3>
  </div>
  
  <div class="signin">
    <% if user_signed_in? %>
      <%= link_to "Logout", destroy_user_session_path, method: :delete %>
    <% else %>
      <%= link_to "Login", new_user_session_path%>
    <% end %>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to "#", class: "navbar-brand" do %>
    <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Home", "#", class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Users", users_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Meetups", meetups_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "My profile", my_account_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= current_user.email %>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Action", "#", class: "dropdown-item" %>
            <%= link_to "Another action", "#", class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/shared/_user-index-card.html.erb
<div class="bh-card-user-index mb-1">
  <div>
    <%= image_tag user.photo || "https://images.unsplash.com/photo-1534528741775-53994a69daeb?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=700&q=80", class: "bh-avatar-sm" %>
  </div>

  <div class="bh-card-user-index-info">
    <p style="font-weight: bold; color: black;"><%= user.first_name %></p>
    <p><%= user.city %></p>
  </div>

  <div class="bh-card-user-index-languages">

    <div class="bh-card-user-index-sharing">
      <div>
        <p>sharing</p>
      <!-- build the progress bar by self -->
      <!-- filter(&:sharing) == filter{|user_language| user_language.sharing} -->

      <div class="language-part">
        <p class="language">
          <% user.user_languages.filter(&:sharing).each do |user_language| %>
          <div class="lang-pro">
            <%=  user_language.language.code %>
            <div style="background-color: #DDDDDD; width: 20px;">
              <div style ="width: <%= user_language.level %>; background-color: #80BD9E; height: 7px;"></div>
            </div>
          </div>
          <% end %>
        </p>
      </div>
    </div>
      </div>


    <div class="bh-card-user-index-practicing">
      <div>
        <p>practicing</p>
      </div>
      <div class="language-part">
        <p class="language">
          <% user.user_languages.filter(&:seeking).each do |user_language| %>
            <div class="lang-pro">
              <%=  user_language.language.code %>
              <div style="background-color: #DDDDDD; width: 20px;">
                <div style ="width: <%= user_language.level %>; background-color: #F49342; height: 7px;"></div>
              </div>

          </div>
          <% end %>
        </p>
      </div>
<!--         <div class="bh-language-icon">
      </div> -->
    </div>

  </div>


</div>

app/views/shared/_user-index-card3.html.erb
<div class="container">
  <div class="bh-card-user-index mb-1">
    <div class="bh-user-index-avatar">
      <%= image_tag user.photo || "https://images.unsplash.com/photo-1534528741775-53994a69daeb?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=700&q=80", class: "bh-avatar-sm" %>
    </div>
    <div class="bh-card-user-index-info">
      <p style="font-weight: bold; color: black;"><%= user.first_name %></p>
      <p style="font-weight: light;"><%= user.city %></p>
    </div>
    <!-- <div class="bh-card-user-index-languages"> -->
    <div class="bh-card-user-index-sharing">
      <div class="language-sharing">
        <div class="text-style">sharing</div>
        <!-- build the progress bar by self -->
        <!-- filter(&:sharing) == filter{|user_language| user_language.sharing} -->

        <div class="language-part">
            <% user.user_languages.filter(&:sharing).each do |user_language| %>
            <div class="lang-pro">
              <div class="language-code"><%=  user_language.language.code %></div>
              <div class="progress-bar">
                <div style="background-color: #DDDDDD; width: 20px;">
                  <div style ="width: <%= user_language.level %>; background-color: #80BD9E; height: 7px; font-size: 12px;"></div>
                </div>
              </div>
            </div>
            <% end %>
        </div>
      </div>
    </div>
    <div class="bh-card-user-index-practicing">
      <div class="language-practicing">
        <div class="text-style">practicing</div>
        <div class="language-part">
            <% user.user_languages.filter(&:seeking).each do |user_language| %>
              <div class="lang-pro">
                <div class="language-code"><%=  user_language.language.code %></div>
                <div class="progress-bar">
                  <div style="background-color: #DDDDDD; width: 20px;">
                    <div style ="width: <%= user_language.level %>; background-color: #F49342; height: 7px; font-size: 12px;"></div>
                  </div>
                </div>
              </div>
            <% end %>
        </div>
      </div>
    </div>
  </div>
</div>